name: Create comment on issue

on:
  issues:
    type:
      - opened

permissions:
  issues: write

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  REPOSITORY: ${{ github.event.repository.full_name }}

jobs:
  create-comment-by-using-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Dumo github event
        run: echo '${{ toJSON(github.event) }}'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ env.TOKEN }}
          repository: ${{ env.REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: "+1"

  create-comment-using-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment using github API
        run: |
          gh api -X POST ${{ env.ISSUE_URL }} -f body="This is a multi-line test comment\n- With GitHub **Markdown** :sparkles:\n- Created by GITHUB API"

        env:
          ISSUE_URL: https://api.github.com/repos/${{ env.REPOSITORY }}/issues/${{ env.ISSUE_NUMBER }}/comments
          GITHUB_TOKEN: ${{ env.TOKEN }}
