name: Create comment on issue

on:
  issues:
    type:
      - opened

permissions:
  issues: write

jobs:
  create-comment-by-using-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Dumo github event
        run: echo '${{ toJSON(github.event) }}'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.repository.full_name }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: "+1"

  create-comment-using-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment using github API
        run: |
          gh api -X POST ${{ env.ISSUE_URL }} -f body='Created by GITHUB API :sparkles'

        env:
          ISSUE_URL: https://api.github.com/repos/${{ github.event.repository.full_name }}/issues/${{ github.event.issue.number }}/comments
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
