name: Create test server for PR

on:
  workflow_dispatch:
    # inputs:
    #   pr_number:
    #     description: Pull request number
    #     required: true

jobs:
  create-testing-branch:
    name: Create testing branch for PR
    runs-on: ubuntu-latest
    steps:
      - name: Validate pull request number
        run: echo "hello there"
