name: Deployment to AWS server

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull Request Number
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR number
        uses: actions/github-script@v7
        id: get-pull-request
        with:
          script: >
            # const response = github.rest.pull.get({
            #   owner: context.repo.owner,
            #   repo: context.repo.repo,
            # })
            echo '${{toJSON(github.event.inputs)}}'
