name: Deployment to AWS server

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull Request Number
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR number
        uses: actions/github-script@v7
        id: get-pull-request
        with:
          result-encoding: string
          script: >
            const response = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.inputs.pr_number }}, 
            })
            echo "${{response}}"
      - name: Get result
        run: echo "${{steps.get-pull-request.outputs.result}}"
