name: Deployment to AWS server

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull Request Number
        required: true
        type: number

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR number
        uses: actions/github-script@v7
        id: get-pull-request
        with:
          result-encoding: string
          script: |
            try {
              const { data: response } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: ${{ github.event.inputs.pr_number }}, 
              })
              console.log(response)
              if (response.state !== 'open' || response.mergeable_state === 'blocked') {
                throw new Error('Either the PR is closed or not in the mergeable state.')
              }
            } catch (err) {
              console.log(err)
              throw new Error('Error fetching PR details')
            }
