name: Hello World Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo hello world
        run: echo "Hello World"

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Echo good bye
        run: echo "Good Bye"
